name: ztexts
version: 0.2.1
description: >-
  A Dart cli tool for fetching and consuming texts.
  Purpose: get texts from a source and send them to a destination.
  Example: from Applanga to Flutter app (i18n) or console log.

homepage: https://github.com/zaraz-digital/ztexts
repository: https://github.com/zaraz-digital/ztexts
issue_tracker: https://github.com/zaraz-digital/ztexts/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  http: ^0.13.3
  yaml: ^3.1.0
  path: ^1.8.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mocktail: ^0.1.2