name: ztexts
version: 0.1.1
description: A simple tool for fetching and consuming texts.
homepage: https://github.com/zaraz-digital/ztexts
repository: https://github.com/zaraz-digital/ztexts
issue_tracker: https://github.com/zaraz-digital/ztexts/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.13.2
  yaml: ^3.1.0
  gen_lang: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4