name: ztexts
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.13.2
  yaml: ^3.1.0
  gen_lang: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4